language: php
php:
  - "7.4"

before_script:
  - composer install

mysql:
  database: metar_test
  username: root
  encoding: utf8

script:
  - php bin/console doctrine:migrations:migration --env=ci -n
  - php bin/console doctrine:fixtures:load --env=ci -n
  - php bin/phpunit