language: php
php:
  - "7.4"

services:
  - mysql

before_script:
  - composer install
  - composer require doctrine/doctrine-fixtures-bundle --dev
  - mysql -e 'CREATE DATABASE IF NOT EXISTS metar_test;'

script:
  - php bin/console doctrine:migrations:migrate --env=ci -n
  - php bin/console doctrine:fixtures:load --env=ci -n
  - php bin/phpunit