language: php
php:
  - "7.4"

before_script:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

mysql:
  database: metar_test
  username: root
  encoding: utf8

install:
  - sudo apt-get php-mysql php-intl php-common

script:
  - php bin/console doctrine:migrations:migration --env=ci -n
  - php bin/console doctrine:fixtures:load --env=ci -n
  - php bin/phpunit